### ISSUE TITLE
dcm2mha conversion not implemented?

### ISSUE THREAD

**Issue by PaWeRe** [DIAGNijmegen/picai_prep#49]
Hi, 

While trying to convert local dicom files to mha for trying the nnUNet and nnDetection inference pipeline provided in [picai_baseline](https://github.com/DIAGNijmegen/picai_baseline), I realized that the "conversion_item()" method in the [converter.py](https://github.com/DIAGNijmegen/picai_prep/blob/5f67119be15e0bdf54d5b97db3e9449f3cc069ed/src/picai_prep/converter.py#L79) is actually not implemented?

If so, do you have any recommendations on how to best convert dicom files to mha, to start the preprocessing process to nnunet raw data archive and nndetection raw data archive? Also, would be good to note the missing conversion implementation in the documentation to notify users in advance :)

Best,

Patrick

PS: It seems the [panimg](https://github.com/DIAGNijmegen/rse-panimg) repo seems to be a good starting point for dicom to mha?

**Comment by joeranbosma** [comment]
Hi @PaWeRe,

The DICOM to MHA conversion is actually implemented. The converter.py file you link contains the base converter class that forms the basis of each of the conversions that are offered by picai_prep.

Converting a DICOM archive can be a bit tricky, because these archives are often organized in different ways across hospitals. Did you follow the steps outlined in the picai_prep documentation?
https://github.com/DIAGNijmegen/picai_prep#dicom-archive--mha-archive

If you know how this can be made more clear to other users, could you make a PR with the proposed changes?

Kind regards,
Joeran

**Comment by joeranbosma** [comment]
Let me know if you have additional concerns, closing this as completed for now.
